from typing import Optional, Literal
from pydantic import BaseModel, Field, field_validator

class AITaskAnalyzeRequest(BaseModel):
    title: str = Field(..., min_length=1, max_length=255, description="Task title to analyze")
    description: Optional[str] = Field(default="", description="Detailed context or problem description")

    @field_validator("title")
    @classmethod
    def validate_title_non_empty(cls, v: str) -> str:
        trimmed = v.strip()
        if not trimmed:
            raise ValueError("Title must not be empty for AI analysis")
        return trimmed

class AITaskAnalyzeResponse(BaseModel):
    priority: Literal["Low", "Medium", "High", "Urgent"] = Field(
        ..., 
        description="Suggested priority level"
    )
    category: str = Field(
        ..., 
        min_length=2, 
        max_length=50, 
        description="Suggested category (e.g., Technical Issue, Bug, Feature Request, Documentation, General)"
    )
    summary: str = Field(
        ..., 
        min_length=5, 
        max_length=500, 
        description="Concise one-sentence summary of the task objective"
    )
    next_action: str = Field(
        ..., 
        min_length=5, 
        max_length=500, 
        description="Actionable first step recommended to resolve or advance the task"
    )
    source: Optional[str] = Field(
        default="gemini-ai", 
        description="Indicates whether result was generated by Google Gemini API or fallback rules"
    )
